### PR TITLE
replace `tokenize_with_phrases` with `phrases` and added tests

### PR DESCRIPTION
**Pull request by cedricconol**
This PR will replace `tokenize_with_phrases` with `phrases`. I added unit tests as well for `phrases`.

This is the result of running `./tests.sh`:
```
..............................................................................................................................................................
----------------------------------------------------------------------
Ran 158 tests in 9.798s

OK
```

This is the result of running `./format.sh`:
```
All done! ✨ 🍰 ✨
6 files left unchanged.
All done! ✨ 🍰 ✨
6 files left unchanged.
```

### CODE REVIEW

**Comment by jbesomi** [comment]
Hey @cedricconol, thank you for your PR! 🎉 

If you look under ["Files Changed"](https://github.com/jbesomi/texthero/pull/101/files) you will notice how it's very hard to see your changes as it appears you replaced the whole file ... this is not optimal as we cannot see clearly what you changed in the code. 

If you look at other PR, for instance #96, you will see that generally, only the code that has been changed is underlined: ["Files Changed"](https://github.com/jbesomi/texthero/pull/96/files)

As it is, I cannot accept the PR, apologize! I encourage you to repeat the process and change only the relevant parts. I cannot help you more than this as I don't know really what happened ...

If you need further assistance, please let me know.

Regards,

**Comment by cedricconol** [comment]
hi @jbesomi, yeah you're right, my bad. This was because I copied and pasted the files from a sandbox directory. Will make adjustments as per your comments. Is it better if make another PR?

**Comment by jbesomi** [comment]
No problem @cedricconol! Yes, opening a PR might work as well or you can just add a new commit, as you prefer.
Regards,

**Comment by cedricconol** [comment]
Please check my latest commits @jbesomi, i hope i did it right this time :smile:

**Comment by jbesomi** [comment]
Hey Cedric!

Well done! 🎉 

Some minor comments:

1. `test_index`: it's probably not necessary to create a new list. You can just add the test under `test_cases_preprocessing`
1. In the docstring, the word "frequrncy" is misspelled. We can also put backtick (\`) around `min_count`
1. `if not isinstance(s.iloc[0], list) or not isinstance(s.iloc[0][0], str):
        raise ValueError("Input series should be a list of string.")`
--> look under [representation/term_frequency](https://github.com/jbesomi/texthero/blob/master/texthero/representation.py) for a slightly better approach to deal with that. The idea is that we tell the user the input should be already tokenized. If not, we tokenize it for him but raise a Warning. If you look at the `test_representation` you can see how to check if the warning is raised correctly.

**Comment by cedricconol** [comment]
hey @jbesomi, kindly check my new commits, i have addressed your comments

**Comment by jbesomi** [comment]
Hey @cedricconol, thank you! This seems all good! 💯  I'm about to leave for a short trip, I will look into that again tomorrow evening or Monday and then merge it!

**Comment by jbesomi** [comment]
Hey Cedric, this seems very good to me!

Review:

1. Why are you doing `delimiter = symbol.encode("utf-8")`, is that necessary?
1. Limit the length of the docstring to 88 characters

**Comment by cedricconol** [comment]
> Hey Cedric, this seems very good to me!
> 
> Review:
> 
> 1. Why are you doing `delimiter = symbol.encode("utf-8")`, is that necessary?
> 2. Limit the length of the docstring to 88 characters

Thanks Jonathan!
1. I have to convert the `symbol` parameter from string to byte string because `PhrasesTransformer` requires the `delimiter` to be a byte string.
2. From #102, this should be 75 characters right? Should I only do this for `phrases`?

**Comment by jbesomi** [comment]
Hey @cedricconol,

Review:

1. There are still some conflicts to fix before I can merge it, can you take care of that?
1. Great you added the test to check for different symbols, that's why unit-test is so crucial ...
1. Unit-test:
    1.  `test_phrases` the name implicate we are testing to see if phrases are made, but as the default, `min_count` is 5 we see no changes from input and output.
    1. I would propose to have four test (or something similar):
           a.`test_phrases` with min_count=2 or 3 to test phrases
           b. `test_phrases_min_count` to check min_count is respected
           c. `test_phrases_threshold` to check threshold is respected
           d. `test_phrases_symbol` with min_count=2 or 3 and a different symbol
  

Sorry for the confusion 75/88. Basically, `black` auto-format maximum line length to 88 characters (for the code), whereas numpy docstring requires 75 characters (for the docstring, but there is no check/auto-formatting for that) ... (I will try to make it more clear in the CONTRIBUTING) and see if we can find a way to check the max length is respected (couldn't find yet)

**Comment by cedricconol** [comment]
Hi @jbesomi,

1. Done fixing the conflicts.
2. I added more tests for `phrases` following your suggestion.
3. Although you haven't mentioned, I kept `test_phrases_not_tokenized_yet`.

**Comment by jbesomi** [comment]
Thank you, Cedric, awesome!! 🎉

**Pull request merged**
