### PR TITLE
Update Docstrings in Visualization Module

### PR DESCRIPTION
**Pull request by henrifroese**
* Fix spelling / too long lines; add hyperlinks; improve explainations

* Add type information in signature (s: pd.Series), ...

* Improve module docstring at the very top

The other (functional) changes to `scatterplot` that were implemented in #107 (overhauling the function + adding 3D support + adding hover_name argument) will be in a separate PR once this is merged.

### CODE REVIEW

**Comment by jbesomi** [comment]
Looks great, thank you! 💪 

Review:

1. Example should be kept short and similar to the rest of the docexamples:
     1. one-line to load data into Pandas
     1. use pd.pipe when applicable
     1. `n_components=3` -> as of now, `pca` with three parameters would fail or at least not work as expected

**Comment by henrifroese** [comment]
Thanks, just did it. I believe the example is now as short as it can be while still showcasing the whole functionality.

**Comment by jbesomi** [comment]
Looks good! Can you just resolve the conflicts, please? Then I will merge it 💪

**Comment by henrifroese** [comment]
> Can you just resolve the conflicts, please?

Done

**Pull request merged**
