### PR TITLE
Added the function to  POS tag

### PR DESCRIPTION
**Pull request by Rickecr**
Added the function to  POS tag.

I saw the suggestions in PR #57 and read the CONTRIBUTING.md file.

Any suggestions please tell me. Thank you!

### CODE REVIEW

**Comment by jbesomi** [comment]
Thank you @Rickecr, that's amazing!! 🎉 🎉 

What if we add also `starting char` and `ending char` as in [texthero.nlp.named_entities](https://texthero.org/docs/api/texthero.nlp.named_entities)? Can you see a value in adding this?

Regarding this comment in #57:

> `batch_size=32`. It would be great if you can do some research and understand which values we should use there. Even better, would be to test it on a concrete example. An alternative would also be to use apply instead of the for-cycle (spacy pipe shuld be multi-threading and that's why I picked this option but making a more in-depth analysis might be useful as-well) It's something you might be interested in? You can start by opening an issue for instance and says that we should focus more on that part. Thanks!

Did you have the occasion to study this problem further? The same question is also asked there as a separate issue #65. Any help with this too would be super appreciated 👌 

---

P.s I have been to Brazil some years ago, Florianopolis, Santa Caterina. I'm missing the vibe and my time there (muita saudade)!! You live in such a beautiful country!

**Comment by Rickecr** [comment]
Hello @jbesomi.

1 - I think it's a good idea to put the `starting char` and `ending char`, because maybe it's important information and I also think it's good to follow the pattern of the functions. Can I add to this PR ?

2 - About the question I even read about it(for this [text](https://prrao87.github.io/blog/spacy/nlp/performance/2020/05/02/spacy-multiprocess.html#Effect-of-chunk-size-and-batch-size)), as I understand it depends on the size of the documents used, so I think it may be a good option to leave this as a parameter for the user, and so he could test with his data. What do you think ?

P.s Thanks for the compliments to my country, the energy here is really good. I hear very good things about your country, hope to visit there one day. And sorry for the bad english.

**Comment by jbesomi** [comment]
1. All right!
2. Ok, but I guess we should do some test and evaluation to at least suggest to users valid values. We will deal with this in a separate PR.

**Comment by Rickecr** [comment]
ready, I will add this change discussed in point 1. And we can deal with the issue of batch size, it is a good idea.

**Comment by Rickecr** [comment]
I'm ready for the review

**Comment by jbesomi** [comment]
Looks great!

Review:

1. The only part that is not 100% clear is the difference between `POS tag` and `The detailed POS tag`. Can you please add a sentence in the docstring explaining the difference between the two?
1. "List of labels:" rename to "List of POS/Tag"? (docstring must be clear, clean and precise)
1. Need to add under the docstring the missing list of POS/Tag 
1. To more details: `POS tagging <https://spacy.io/api/annotation#pos-tagging>` -> we want to provide to the users already all required information to use such function. At the same time though, we want to show where this solution comes from ...
Look at the other code, something like "Internally `noun_chunks` makes use of Spacy's dependency parsing:
    https://spacy.io/usage/linguistic-features#dependency-parse" might be more appropriate ...

**Comment by Rickecr** [comment]
Hey @jbesomi . I made the requested changes, less the number 3, because I could not find a list of absence of POS / tag. I only found information about the POS/Tag list:

- List of POS/Tag: https://spacy.io/api/annotation#pos-universal
- Universal POS tags: https://universaldependencies.org/u/pos/

**Comment by jbesomi** [comment]
Thank you @Rickecr, merged!

And officially welcome to Texthero's contributors! You can now open a new PR and add your name under README.md - contributors! 👍 🎉 🎉

**Pull request merged**
