### PR TITLE
Adding the missing arguments to wordcloud func. Closes #77

### LINKED ISSUE #77: WordCloud: TypeError: wordcloud() got an unexpected keyword argument 'min_font_size' and 'max_font_size'
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-58-9c76fea65749> in <module>()
----> 1 hero.visualization.wordcloud(df1['clean_tweet'],width = 200, height= 200,background_color='White',min_font_size=2)

TypeError: wordcloud() got an unexpected keyword argument 'min_font_size'
```

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-63-951ae06e0982> in <module>()
----> 1 hero.visualization.wordcloud(df1['clean_tweet'],width = 200, height= 200,background_color='White',max_font_size=8)

TypeError: wordcloud() got an unexpected keyword argument 'max_font_size'
```

I am working on Google Colab and tried using the argument `min_font_size` to change it from `default` value `4` to `2`. But it gives me a TypeError.

Although the [documentation](https://texthero.org/docs/api/texthero.visualization.wordcloud) says the method has the argument, it doesn't take in this argument when changed to another value.

Was this feature removed or yet to be added?

### PR DESCRIPTION
**Pull request by vidyap-xgboost**
Added the missing arguments to the word cloud function as per the documentation provided.

### CODE REVIEW

**Comment by vidyap-xgboost** [comment]
> Added the missing arguments to the word cloud function as per the documentation provided.

Any suggestions in writing a unittest for wordcloud is welcome! Thank you!

**Comment by vidyap-xgboost** [comment]
> > Added the missing arguments to the word cloud function as per the documentation provided.
> 
> Any suggestions in writing a unittest for wordcloud is welcome! Thank you!

Tested this on terminal as below:

```python
>>> import texthero as hero
>>> import pandas as pd
>>> df = pd.read_csv('https://github.com/jbesomi/texthero/raw/master/dataset/bbcsport.csv')
>>> hero.visualization.wordcloud(df['text'],width = 400, height= 400,background_color='White',min_font_size=6)
>>> hero.visualization.wordcloud(df['text'],width = 400, height= 400,background_color='White',max_font_size=6)
>>> import matplotlib
>>> matplotlib.pyplot.show(block=True)
>>> hero.visualization.wordcloud(df['text'],width = 400, height= 400,background_color='White',min_font_size=10)
>>> matplotlib.pyplot.show(block=True)
>>> hero.visualization.wordcloud(df['text'],width = 400, height= 400,background_color='White',min_font_size=1)
>>> matplotlib.pyplot.show(block=True)
>>> hero.visualization.wordcloud(df['text'],width = 400, height= 400,background_color='White',max_font_size=10)
>>> matplotlib.pyplot.show(block=True)
>>> 
```

**Comment by vidyap-xgboost** [comment]
max_font_size=10:
Figure_1

min_font_size=1:
Figure_2

min_font_size=20:
Figure_3

**Comment by jbesomi** [comment]
Thank you!

Unit-testing this function is not trivial as the result is an image. Something that can be done (but's probably not necessary and too complex) is to use the `.to_svg()` function (see [Wordcloud API](https://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud) ) and then do some unit-test at the SVG level ... 

Review:

1. Thank you!
2. Did you check manually that the docstring for the API is correct (no English mistake), the parameters in the docstring are in  the same order as the parameters of the function (we might want to group together *_font_size?) and that all parameters are passed at the _Wordcloud_ object? If yes, then we are good!
3. What about issue #78? Did you find a way to have an image in high quality?
 
General comment:
(to let you participate in a broader discussion)

To go from the raw text data to the single word (token), "tokenize" the text (`s.str.cat(sep=" ").split()`). A valid alternative might be to receive as input a TokenSeries (see #60 for extra information); that way there are no hidden behavior that the user cannot see ... this discussion can be amplified further and we can argue that _almost_ all hero functions should receive as input a `TokenSeries` ...

**Comment by jbesomi** [comment]
I think this part deserves a small article too! ;) Images looks beautiful!

**Comment by vidyap-xgboost** [comment]
> Thank you!
> 
> Unit-testing this function is not trivial as the result is an image. Something that can be done (but's probably not necessary and too complex) is to use the `.to_svg()` function (see [Wordcloud API](https://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud) ) and then do some unit-test at the SVG level ...
> 
> Review:
> 
> 1. Thank you!
> 2. Did you check manually that the docstring for the API is correct (no English mistake), the parameters in the docstring are in  the same order as the parameters of the function (we might want to group together *_font_size?) and that all parameters are passed at the _Wordcloud_ object? If yes, then we are good!
> 3. What about issue #78? Did you find a way to have an image in high quality?
> 
> General comment:
> (to let you participate in a broader discussion)
> 
> To go from the raw text data to the single word (token), "tokenize" the text (`s.str.cat(sep=" ").split()`). A valid alternative might be to receive as input a TokenSeries (see #60 for extra information); that way there are no hidden behavior that the user cannot see ... this discussion can be amplified further and we can argue that _almost_ all hero functions should receive as input a `TokenSeries` ...

1. I will read further on how to unit test a word cloud and if I think I can do it, I will create a PR. :+1: 
2. I've checked the docstring for the API and have cross-checked all the parameters and yes, everything is proper!
3. I'm attaching another picture in relation to #78 

>>> hero.visualization.wordcloud(df['text'],width = 400, height= 200,background_color='White',min_font_size=6)
>>> matplotlib.pyplot.show(block=True)

Figure_4

As you can see the image still has some 'blur' in them when I change `width=400, height=200`. However, I will be working on making it better and soon create a PR once I figure it out. But to introduce no blur in the image it is advised to have width and height equal, in my previous images, I used `width=400, height=400`.

**Comment by vidyap-xgboost** [comment]
@jbesomi Thank you for involving me in the discussion. I'll have a look at #60 and update myself about it. :smiley:

**Comment by jbesomi** [comment]
Good to know that having the same width and size reduce blurs; this is valuable information we might add in the docstring.
I'm gonna merge and close this for now. It's up-to-you to leave open or close the related issues.

**Comment by vidyap-xgboost** [comment]
> Thank you!
> 
> Unit-testing this function is not trivial as the result is an image. Something that can be done (but's probably not necessary and too complex) is to use the `.to_svg()` function (see [Wordcloud API](https://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud) ) and then do some unit-test at the SVG level ...
> 
> Review:
> 
> 1. Thank you!
> 2. Did you check manually that the docstring for the API is correct (no English mistake), the parameters in the docstring are in  the same order as the parameters of the function (we might want to group together *_font_size?) and that all parameters are passed at the _Wordcloud_ object? If yes, then we are good!
> 3. What about issue #78? Did you find a way to have an image in high quality?
> 
> General comment:
> (to let you participate in a broader discussion)
> 
> To go from the raw text data to the single word (token), "tokenize" the text (`s.str.cat(sep=" ").split()`). A valid alternative might be to receive as input a TokenSeries (see #60 for extra information); that way there are no hidden behavior that the user cannot see ... this discussion can be amplified further and we can argue that _almost_ all hero functions should receive as input a `TokenSeries` ...


> Good to know that having the same width and size reduce blurs; this is valuable information we might add in the docstring.
> I'm gonna merge and close this for now. It's up-to-you to leave open or close the related issues.

Thanks! I will be closing #77 and work on #78 (will update in comments regarding width and height being equal).

**Pull request merged**
