### PR TITLE
Add _check_tokenized function

### PR DESCRIPTION
**Pull request by AlfredWGA**
- Add a `_check_tokenized` function, avoid writing checking codes for each API.
- Add VS Code project setting folder `.vscode` to `.gitignore`.

### CODE REVIEW

**Comment by jbesomi** [comment]
Hey @AlfredWGA, thank you! 🎉 🎉 

Review:

1. That's a great idea, thanks! 👍 
1. What if we create a new private module `_helper` or something similar and move `_check_tokenized ` under there? As there will be other functions not in `representation` that will need to do the same check (see for instance #101)
1. As per #60, such Pandas Series `s` will be referenced as `TokenSeries`. What if we rename the method to `_is_tokenseries` or `_check_is_tokenseries` or something similar? In the future, then we will also have `is_representationseries` and so on
1. (minor comment) In the future, if that's possible, it would be great if you can keep the PR [self-contained](https://github.com/jbesomi/texthero/blob/master/CONTRIBUTING.md#best-practices) and avoid to do two different things. This is a [good article](https://opensource.zalando.com/blog/2017/10/small-pull-requests/) if you are interested in why. For this time, this is perfectly fine as the _gitignore_ changes are minimal

Regards,

**Comment by jbesomi** [comment]
Note also the relation with #69

**Comment by AlfredWGA** [comment]
Indeed #69 is a great solution for all these checking problem. I'll wait until that PR is completed and see what I can do further.

**Comment by henrifroese** [comment]
Closing this as #69 is merged with this functionality.

**Pull request closed without merging**
